version: '3.5'
services:
  dns_server:
    image: m400/technitium
    networks:
      technitium-network:
        aliases:
          - technitium-dns
    ports:
    - 53:53/udp
    - 53:53/tcp
    - 67:67/udp
    - 5380:5380
    volumes:
    - data:/app/config
    restart: unless-stopped
volumes:
  data:
networks:
  technitium-network:
